name: iot
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20211102.0
  - annotated-types=0.6.0
  - anyio=3.5.0
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=11.0.0
  - asttokens=2.0.5
  - attrs=22.1.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - boost-cpp=1.73.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2024.2.2
  - catalogue=2.0.10
  - certifi=2024.2.2
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cleanco=2.2
  - click=8.0.4
  - cloudpathlib=0.16.0
  - colorama=0.4.6
  - comm=0.1.2
  - confection=0.1.4
  - cramjam=2.6.2
  - cryptography=41.0.2
  - cuda-cccl=12.2.128
  - cuda-cudart=11.7.99
  - cuda-cudart-dev=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-libraries-dev=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvrtc-dev=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cycler=0.11.0
  - cymem=2.0.8
  - cython-blis=0.7.10
  - dataclasses=0.8
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.7
  - dnspython=2.2.1
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - fastparquet=2023.4.0
  - filelock=3.9.0
  - freetype=2.12.1
  - fsspec=2023.4.0
  - fuzzywuzzy=0.18.0
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.69.1
  - glog=0.5.0
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - icc_rt=2022.1.0
  - icu=58.2
  - importlib-metadata=7.0.1
  - intel-openmp=2023.1.0
  - ipykernel=6.19.2
  - ipython=8.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_server=1.13.5
  - jupyterlab=3.3.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.3
  - jupyterlab_widgets=3.0.5
  - kiwisolver=1.4.5
  - krb5=1.19.4
  - langcodes=3.3.0
  - lerc=3.0
  - libboost=1.73.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=11.10.3.66
  - libcublas-dev=11.10.3.66
  - libcufft=10.7.2.124
  - libcufft-dev=10.7.2.124
  - libcurand=10.3.3.129
  - libcurand-dev=10.3.3.129
  - libcurl=8.1.1
  - libcusolver=11.4.0.1
  - libcusolver-dev=11.4.0.1
  - libcusparse=11.7.4.91
  - libcusparse-dev=11.7.4.91
  - libdeflate=1.17
  - libffi=3.4.4
  - libiconv=1.16
  - libnpp=11.7.4.75
  - libnpp-dev=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libnvjpeg-dev=11.8.0.2
  - libogg=1.3.5
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libthrift=0.15.0
  - libtiff=4.5.0
  - libuv=1.44.2
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.3
  - libxslt=1.1.37
  - lxml=4.9.2
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown-it-py=3.0.0
  - markupsafe=2.1.1
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mdurl=0.1.2
  - mistune=0.8.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - multiprocess=0.70.15
  - munkres=1.1.4
  - murmurhash=1.0.10
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - nest-asyncio=1.5.6
  - networkx=3.1
  - nltk=3.8.1
  - notebook=6.5.4
  - notebook-shim=0.2.2
  - numexpr=2.8.4
  - openpyxl=3.0.10
  - openssl=1.1.1w
  - orc=1.7.4
  - packaging=23.0
  - pandas=1.5.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathos=0.3.0
  - pathy=0.10.2
  - patsy=0.5.3
  - pcre=8.45
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.2.1
  - platformdirs=2.5.2
  - ply=3.11
  - pooch=1.4.0
  - pox=0.3.3
  - ppft=1.7.6.7
  - preshed=3.0.9
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pyarrow=11.0.0
  - pycparser=2.21
  - pydantic=2.6.2
  - pydantic-core=2.16.3
  - pyexecjs=1.5.1
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pypdf2=2.10.5
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.11.4
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-levenshtein=0.12.2
  - python_abi=3.11
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytz=2022.7
  - pywin32=305
  - pywinpty=2.0.10
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.4.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - re2=2022.04.01
  - regex=2022.7.9
  - requests=2.31.0
  - requests-file=1.5.1
  - rich=13.7.0
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - seaborn=0.12.2
  - selenium=3.141.0
  - send2trash=1.8.0
  - setuptools=68.0.0
  - shellingham=1.5.4
  - sip=6.6.2
  - six=1.16.0
  - smart_open=5.2.1
  - snappy=1.1.9
  - sniffio=1.2.0
  - soupsieve=2.4
  - spacy=3.7.2
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - sqlite=3.41.2
  - srsly=2.4.8
  - stack_data=0.2.0
  - statsmodels=0.14.0
  - sympy=1.11.1
  - tbb=2021.8.0
  - terminado=0.17.1
  - thefuzz=0.19.0
  - thinc=8.2.2
  - threadpoolctl=2.2.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - tldextract=3.2.0
  - toml=0.10.2
  - tornado=6.3.2
  - tqdm=4.65.0
  - traitlets=5.7.1
  - translators=5.9.0
  - typer=0.9.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - ucrt=10.0.22621.0
  - urllib3=1.26.16
  - utf8proc=2.6.1
  - vc=14.2
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wasabi=1.1.2
  - wcwidth=0.2.5
  - weasel=0.3.4
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  - widgetsnbextension=4.0.5
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - abydos==0.5.0
    - aiohttp==3.9.3
    - aiosignal==1.3.1
    - bs4==0.0.2
    - chardet==3.0.4
    - cloudpickle==2.2.1
    - contourpy==1.1.0
    - cssselect==1.2.0
    - deep-translator==1.11.4
    - deprecation==2.1.0
    - distro==1.9.0
    - dpkt==1.9.8
    - en-core-web-lg==3.7.1
    - en-core-web-md==3.7.1
    - enchant==0.0.1
    - fake-useragent==1.4.0
    - fonttools==4.42.1
    - frozenlist==1.4.1
    - future==1.0.0
    - googletrans==3.0.0
    - h11==0.9.0
    - h2==3.2.0
    - hpack==3.0.0
    - hstspreload==2023.1.1
    - httpcore==0.9.1
    - httpx==0.13.3
    - huggingface-hub==0.16.4
    - hyperframe==5.2.0
    - idna==2.10
    - ifaddr==0.2.0
    - imbalanced-learn==0.11.0
    - influxdb==5.3.1
    - iniconfig==2.0.0
    - langdetect==1.0.7
    - langid==1.1.6
    - llvmlite==0.41.0
    - msgpack==1.0.5
    - multidict==6.0.5
    - netdisco==3.0.0
    - nfstream==6.5.3
    - numba==0.58.0
    - numpy==1.23.2
    - openai==0.27.4
    - parse==1.20.1
    - pdfminer==20191125
    - pluggy==1.2.0
    - publicsuffixlist==0.10.0.20230730
    - pycryptodome==3.18.0
    - pyee==11.1.0
    - pyppeteer==2.0.0
    - pyquery==2.0.0
    - pytest==7.4.0
    - python-whois==0.8.0
    - pyvirtualdisplay==3.0
    - requests-html==0.10.0
    - rfc3986==1.5.0
    - safetensors==0.3.2
    - scapy==2.5.0
    - shap==0.42.1
    - slicer==0.0.7
    - spacy-langdetect==0.1.2
    - stopit==1.1.2
    - tokenizers==0.13.3
    - torchaudio==2.0.2
    - torchvision==0.15.2
    - transformers==4.31.0
    - urltools2==0.3.2
    - w3lib==2.1.2
    - websockets==10.4
    - xformers==0.0.21
    - xgboost==2.0.0
    - yarl==1.9.4
    - zeroconf==0.120.0
prefix: C:\Users\mjakari\Anaconda3\envs\iot
